// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpWyVj9CdtgwbsSHMdkp_Gq3ThhXRbLSQ',
    appId: '1:1092203992902:web:82a6cc1a1b71f8c95d3747',
    messagingSenderId: '1092203992902',
    projectId: 'event-project-e6868',
    authDomain: 'event-project-e6868.firebaseapp.com',
    storageBucket: 'event-project-e6868.firebasestorage.app',
    measurementId: 'G-FHED69FK5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqCuNwFwmUQbwUUXdJww39JOpj2TvJ444',
    appId: '1:1092203992902:android:4a434b235fd3ee695d3747',
    messagingSenderId: '1092203992902',
    projectId: 'event-project-e6868',
    storageBucket: 'event-project-e6868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4cz_2T3i4WalS0svkIP5lsyZvg5ATG98',
    appId: '1:1092203992902:ios:8e1208d50d54b0315d3747',
    messagingSenderId: '1092203992902',
    projectId: 'event-project-e6868',
    storageBucket: 'event-project-e6868.firebasestorage.app',
    iosBundleId: 'bj.mymood.eventBj',
  );
}
